name: cs229_project
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch
    - torchvision 
    - torchaudio
    - tqdm
    - requests
    - importlib-metadata
    - filelock
    - scikit-learn
    - tokenizers
    - xgboost
    - matplotlib
    - numpy
    - pandas
    - seaborn
    - jupyter
    - notebook
    - ipykernel
    - ipywidgets
